# datasets
datasets: office_home

# Backbone
model_name: resnet50

# Optimizer related
lr: 3e-4
weight_decay: 5e-4
momentum: 0.9
label_smoothing: 0.1
l_batch_size: 32
u_batch_size: 32

# Loss related
clf_factor: 0.5
cpa_factor: 1.0
cgi_factor: 0.025

# scheduler related
scheduler: True
lr_gamma: 0.0003
lr_decay: 0.75
multiple_lr_classifier: 10

# Training related
n_iter_per_epoch: 500
n_epoch: 20
pda: True

# Others
seed: 42
num_workers: 4
